# Generated by Django 6.0.1 on 2026-01-20 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('spaceowner', '0004_advertisementspace_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='spaceowner.advertisementspace'),
            preserve_default=False,
        ),
    ]
