# Generated by Django 6.0.1 on 2026-01-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_active_user_is_suspend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adharnumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_suspend',
            field=models.BooleanField(default=True),
        ),
    ]
