# Generated by Django 6.0.1 on 2026-02-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_advertiser_alter_booking_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_to_adspora',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
    ]
