# Generated by Django 6.0.1 on 2026-02-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_amount_to_adspora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='amount_to_adspora',
            new_name='platform_fee',
        ),
    ]
