# Generated by Django 6.0.1 on 2026-01-14 11:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaceowner', '0002_alter_advertisementspace_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
