# Generated by Django 6.0.1 on 2026-01-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceowner', '0003_alter_spaceimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementspace',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
